### PR TITLE
Better equations

### PR DESCRIPTION
**Pull request by mthorrell**
Addressing issue #17. This uses a URL embedding from https://www.codecogs.com/latex/eqneditor.php... not sure if there is a better way to do this.

### CODE REVIEW

**Comment by mthorrell** [comment]
The y in the paragraph (just above the table) is kinda weird. What are your thoughts on removing from math mode and just leaving as plain x and y?

**Comment by mfrasco** [comment]
Thanks so much for doing all of this. The only downside to this solution is that it can take a while for the images to load onto github. Even after I refresh a couple of times, I can't even get the x and y to download on the page.

**Comment by mfrasco** [comment]
And I fully agree that x and y should not be in math mode. You can remove the link to the latex and use plain text.

**Comment by mthorrell** [comment]
I removed the x and y from the tex formatting. The images really take a long time to load? When I view the readme in my branch it seems to load pretty immediately: https://github.com/mthorrell/Metrics/tree/better-equations

**Comment by jameslamb** [comment]
To add another data point.. @mthorrell I went to [this branch on your fork](https://github.com/mthorrell/Metrics/blob/better-equations/README.md) and can confirm that the equations also loaded super fast for me. Tried it in Chrome, Firefox, and Safari.

**Pull request merged**
